# these are executed in order.
stages:
  - lint # lint code and docs
  - test # all tests

language: node_js
node_js:
  - "8"
branches:
  only:
    - master
notifications:
  email:
    - chrissanz@gmail.com